import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

describe('official file plugin contract fixture', () => {
  it('requests the protocol artifacts generated by file ingestion', async () => {
    const path = fileURLToPath(new URL('../sheldon-plugin.contract.json', import.meta.url));
    const fixture = JSON.parse(await readFile(path, 'utf8')) as {
      ingest: { input: { canonicalUri?: string; filePath?: string }; expectedRoles: string[] };
    };

    expect(fixture.ingest).toEqual({
      input: {
        filePath: '../../../../test-fixtures/ingestion/files/sample.md',
        canonicalUri: 'file:///fixtures/sample.md',
      },
      options: {},
      expectedRoles: ['original', 'normalized'],
    });
  });
});
