import { describe, expect, it, vi } from 'vitest';

import { normalizeYoutubeMarkdown, selectYoutubeCaption } from '../src/captions.js';
import type { YoutubeCaptionCandidate } from '../src/yt-dlp.js';

const manualPt: YoutubeCaptionCandidate = {
  path: '/captions/pt-manual.vtt',
  language: 'pt',
  kind: 'manual',
};
const automaticPt: YoutubeCaptionCandidate = {
  path: '/captions/pt-automatic.vtt',
  language: 'pt',
  kind: 'automatic',
};
const manualEn: YoutubeCaptionCandidate = {
  path: '/captions/en-manual.vtt',
  language: 'en',
  kind: 'manual',
};

describe('selectYoutubeCaption', () => {
  it('prefers a manual track for the first requested language and normalizes its VTT text', async () => {
    const readCaption = vi
      .fn()
      .mockResolvedValue(
        [
          'WEBVTT',
          '',
          'first-cue',
          '00:00:00.000 --> 00:00:01.000 align:start position:0%',
          '<c.green>Primeira linha</c>',
          '',
          '00:00:01.000 --> 00:00:02.000',
          'Primeira linha',
          '',
          '00:00:02.000 --> 00:00:03.000',
          'Segunda linha',
          '',
        ].join('\n'),
      );

    await expect(
      selectYoutubeCaption({
        candidates: [automaticPt, manualEn, manualPt],
        languages: ['pt', 'en'],
        readCaption,
      }),
    ).resolves.toEqual({
      candidate: manualPt,
      text: 'Primeira linha\nSegunda linha\n',
      warnings: [],
    });
    expect(readCaption).toHaveBeenCalledTimes(1);
    expect(readCaption).toHaveBeenCalledWith(manualPt.path);
  });

  it('uses path order within a kind and falls back from unusable manual captions to automatic captions', async () => {
    const laterManual: YoutubeCaptionCandidate = { ...manualPt, path: '/captions/z.vtt' };
    const earlierManual: YoutubeCaptionCandidate = { ...manualPt, path: '/captions/a.vtt' };
    const readCaption = vi.fn(async (path: string) => {
      if (path === earlierManual.path) return 'WEBVTT\n\n00:00:00.000 --> 00:00:01.000\n\n';
      if (path === automaticPt.path)
        return 'WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nLegenda automática\n';
      throw new Error(`Unexpected path: ${path}`);
    });

    await expect(
      selectYoutubeCaption({
        candidates: [laterManual, automaticPt, earlierManual],
        languages: ['pt'],
        readCaption,
      }),
    ).resolves.toEqual({
      candidate: automaticPt,
      text: 'Legenda automática\n',
      warnings: ['Skipped unusable caption pt.manual.', 'Skipped unreadable caption pt.manual.'],
    });
    expect(readCaption).toHaveBeenNthCalledWith(1, earlierManual.path);
    expect(readCaption).toHaveBeenNthCalledWith(2, laterManual.path);
    expect(readCaption).toHaveBeenNthCalledWith(3, automaticPt.path);
  });

  it('removes WebVTT notes, styles, and region declarations instead of treating them as transcript text', async () => {
    const readCaption = vi
      .fn()
      .mockResolvedValue(
        [
          'WEBVTT',
          '',
          'NOTE generated by yt-dlp',
          'not a caption',
          '',
          'STYLE',
          '::cue { color: lime; }',
          '',
          'REGION id=bottom width=40%',
          'lines:3',
          '',
          '00:00:00.000 --> 00:00:01.000',
          'Texto da legenda',
        ].join('\n'),
      );

    await expect(
      selectYoutubeCaption({ candidates: [manualPt], languages: ['pt'], readCaption }),
    ).resolves.toMatchObject({ text: 'Texto da legenda\n' });
  });

  it('skips arbitrary header metadata and timestamps with three-digit hours', async () => {
    const readCaption = vi
      .fn()
      .mockResolvedValue(
        [
          'WEBVTT - generated captions',
          'Title: Session',
          'Custom-Metadata: ignored',
          '',
          '100:00:00.000 --> 100:00:01.000 align:start',
          'Legenda após cem horas',
        ].join('\n'),
      );

    await expect(
      selectYoutubeCaption({ candidates: [manualPt], languages: ['pt'], readCaption }),
    ).resolves.toMatchObject({ text: 'Legenda após cem horas\n' });
  });

  it('fails with an actionable stable code when no candidate produces text', async () => {
    await expect(
      selectYoutubeCaption({
        candidates: [],
        languages: ['pt'],
        readCaption: vi.fn(),
      }),
    ).rejects.toThrow(
      'YOUTUBE_CAPTIONS_UNAVAILABLE: No usable requested captions were available. Local speech-to-text fallback is not implemented; retry with another requested language or provide a captioned source.',
    );
  });

  it('matches requested and candidate BCP-47 tags case-insensitively and normalizes the result', async () => {
    const mixedCase: YoutubeCaptionCandidate = {
      path: '/captions/pt-br.vtt',
      language: 'PT-BR',
      kind: 'manual',
    };

    await expect(
      selectYoutubeCaption({
        candidates: [mixedCase],
        languages: ['pt-br'],
        readCaption: vi
          .fn()
          .mockResolvedValue('WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nOlá Brasil\n'),
      }),
    ).resolves.toMatchObject({
      candidate: { language: 'pt-br', kind: 'manual' },
      text: 'Olá Brasil\n',
    });
  });
});

describe('normalizeYoutubeMarkdown', () => {
  it('renders escaped metadata, caption provenance, and transcript in deterministic Markdown', () => {
    const result = normalizeYoutubeMarkdown({
      canonicalUri: 'https://www.youtube.com/watch?v=AbCdEf12345',
      info: {
        title: 'Talk #1 [draft]',
        uploader: 'Ada Lovelace',
        upload_date: '20260724',
        duration: 90,
        description: 'Notes',
      },
      caption: { candidate: manualPt, text: 'Primeira linha\nSegunda linha\n', warnings: [] },
      ytDlpVersion: '2026.07.01',
    });

    expect(result).toEqual({
      content: [
        '# Talk \\#1 \\[draft\\]',
        '',
        '- Source: https://www.youtube.com/watch?v=AbCdEf12345',
        '- Uploader: Ada Lovelace',
        '- Upload date: 2026-07-24',
        '- Duration: 90 seconds',
        '- Caption: pt (manual)',
        '- yt-dlp: 2026.07.01',
        '',
        '## Description',
        '',
        'Notes',
        '',
        '## Transcript',
        '',
        'Primeira linha',
        'Segunda linha',
        '',
      ].join('\n'),
      warnings: [],
    });
  });
});
